name: CD

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - run: npm install
    - run: npm run production
    - name: Commit built assets
      run: |
        git config --local user.email "jacosmonjurajad@gmail.com"
        git config --local user.name "Jacos-Monjur"
        git checkout -B deploy
        git add -f public/
        git commit -m "Build front-end assets"
        git push -f origin deploy
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USER_NAME }}
        host: ${{ secrets.HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/html && /../deploy.sh'
